server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /health {
    default_type text/plain;
    return 200 'ok';
  }

  location = /movie-search-app/health {
    default_type text/plain;
    return 200 'ok';
  }

  location /movie-search-app/ {
    try_files $uri $uri/ /movie-search-app/index.html;
  }

  location / {
    return 302 /movie-search-app/;
  }
}
